//
//  NewModel.swift
//  SafeFun
//
//  Created by Facultad de Contaduría y Administración on 21/10/25.
//
import SwiftUI

struct NewsArticle: Identifiable {
    let id: UUID
    let city: String
    let title: String
    let publishDate: Date
    let author: String
    let imageName: String
    let fullText: String
    
    init(city: String, title: String, publishDate: Date = Date(), author: String, imageName: String, fullText: String) {
        self.id = UUID()
        self.city = city
        self.title = title
        self.publishDate = publishDate
        self.author = author
        self.imageName = imageName
        self.fullText = fullText
    }
}

// --- MOCK DATABASE ---
extension NewsArticle {
    static let allNewsArticles: [NewsArticle] = [
        // MARK: - USA CITIES (11)
        
        // Atlanta
        NewsArticle(city: "Atlanta", title: "Atlanta Police Announce City-Wide Security Grid", author: "Maria Garcia", imageName: "Atlanta", fullText: "The Atlanta Police Department, in collaboration with federal partners, has announced a comprehensive city-wide security grid to ensure the safety of all residents and visitors during the World Cup. This multi-layered strategy includes increased patrols in high-traffic areas such as downtown, Midtown, and the areas surrounding Mercedes-Benz Stadium. Over 2,000 additional officers will be deployed, with specialized units focusing on counter-terrorism, traffic management, and public order. Command centers will monitor a network of over 15,000 CCTV cameras 24/7."),
        NewsArticle(city: "Atlanta", title: "Mercedes-Benz Stadium Deploys AI-Powered Screening", author: "John Smith", imageName: "Atlanta", fullText: "Mercedes-Benz Stadium is setting a new standard for venue security with the implementation of an advanced AI-powered screening system. This touchless technology allows fans to enter the stadium without removing items from their pockets or bags, significantly speeding up entry times while enhancing threat detection. The system can distinguish between everyday items like phones and keys and prohibited items, flagging potential concerns for secondary screening. Officials state this will create a safer and more seamless experience for the hundreds of thousands of fans attending matches."),
        NewsArticle(city: "Atlanta", title: "MARTA Enhances Transit Security for Tournament", author: "Emily White", imageName: "Atlanta", fullText: "The Metropolitan Atlanta Rapid Transit Authority (MARTA) has bolstered its security measures across all train and bus lines. Commuters will notice a significant increase in uniformed officers and K-9 units patrolling stations and vehicles. In addition to visible security, MARTA has upgraded its surveillance systems with higher-resolution cameras and real-time monitoring capabilities linked directly to the central police command. These efforts are designed to provide a secure and reliable transportation option for fans traveling to matches and other city-wide events during the World Cup."),

        // Boston
        NewsArticle(city: "Boston", title: "Multi-Agency Task Force to Secure Boston Fan Zones", author: "Chris Lee", imageName: "Boston", fullText: "A multi-agency task force comprising the Boston Police Department, Massachusetts State Police, and FBI has been established to oversee security at all official fan zones. These zones, located at City Hall Plaza and the Seaport, will feature perimeter fencing, bag checks, and a heavy police presence. Undercover officers will also be deployed to monitor crowds and identify any potential disruptions. The goal is to create a family-friendly and secure environment where fans can safely enjoy the matches on large screens and participate in festivities without concern."),
        NewsArticle(city: "Boston", title: "Gillette Stadium Enforces Strict No-Bag Policy", author: "David Chen", imageName: "Boston", fullText: "Gillette Stadium has announced a strict no-bag policy for all World Cup matches to enhance security and expedite entry. Only small clutch bags, no larger than a hand, will be permitted. All other bags, including backpacks and purses, are strictly prohibited. Fans are encouraged to pack light and utilize lockers that will be available for rent near the stadium entrances. This policy, common in the NFL, is being adopted to minimize potential threats and create a more secure environment inside the venue for all attendees."),
        NewsArticle(city: "Boston", title: "MBTA Increases Patrols on Commuter Rail Lines", author: "Jessica Miller", imageName: "Boston", fullText: "The MBTA has significantly increased its security presence on all Commuter Rail lines, particularly the Providence/Stoughton Line serving Gillette Stadium. Transit Police will be conducting random bag checks and will have an increased number of officers riding the trains on match days. The 'See Something, Say Something' campaign will be heavily promoted, with clear instructions on how to discreetly report suspicious activity to authorities using the MBTA's dedicated security app."),

        // Dallas
        NewsArticle(city: "Dallas", title: "Dallas Command Center Integrates Regional Security", author: "Michael Brown", imageName: "Dallas", fullText: "The City of Dallas has activated a state-of-the-art Joint Operations Center (JOC) that integrates feeds and communications from police departments across the Metroplex, including Arlington and Fort Worth. This centralized command hub will allow for real-time coordination of security assets, traffic management, and emergency response. Federal agencies like the Department of Homeland Security will also have a presence in the JOC to provide intelligence and support for the duration of the tournament, ensuring a unified security front across the entire region."),
        NewsArticle(city: "Dallas", title: "AT&T Stadium to Use Drone Surveillance for Perimeter Security", author: "Jennifer Davis", imageName: "Dallas", fullText: "AT&T Stadium will deploy a fleet of security drones to monitor the extensive perimeter and parking lots during match days. These drones are equipped with high-resolution and thermal cameras, providing security personnel with an aerial overview of the entire complex. The system is designed to detect unauthorized drones, identify suspicious activity in real-time, and help manage crowd flow before and after matches. This proactive surveillance measure is part of a high-tech security overlay designed to protect one of the world's largest sports venues."),
        NewsArticle(city: "Dallas", title: "DART Light Rail Increases Security Checks at Stations", author: "Kevin Wilson", imageName: "Dallas", fullText: "Dallas Area Rapid Transit (DART) will implement increased security protocols across its light rail system. Fans traveling to Fair Park and other central locations will encounter a higher visibility of DART Police officers and fare enforcement officials. K-9 units trained in explosive detection will be performing sweeps at key stations, including Victory Station and the lines serving the stadium. DART is committed to maintaining a safe and efficient transit environment for the millions of visitors expected to use the system."),

        // Houston
        NewsArticle(city: "Houston", title: "Houston PD Unveils 'Tourist Safety Zones' Program", author: "Sarah Johnson", imageName: "Houston", fullText: "Houston Police have designated several 'Tourist Safety Zones' in high-traffic areas like the Galleria, Museum District, and Downtown. These zones will feature an increased officer presence, mobile information kiosks with multilingual staff, and enhanced lighting. The initiative is designed to provide visitors with safe and welcoming areas to explore the city's attractions. A dedicated hotline and app feature will allow tourists to quickly report any concerns and receive immediate assistance, ensuring a positive and secure experience in Houston."),
        NewsArticle(city: "Houston", title: "NRG Stadium Implements Advanced Credentialing System", author: "Daniel Taylor", imageName: "Houston", fullText: "A new digital credentialing system is being implemented at NRG Stadium for all staff, media, and players to enhance access control security. The system uses biometric data to verify identities, preventing unauthorized access to restricted areas. This technology ensures that only vetted and approved individuals can enter sensitive zones like locker rooms and operational command posts. It represents a significant upgrade from traditional laminated passes and is a key part of the venue's comprehensive security plan to protect the integrity of the event."),
        NewsArticle(city: "Houston", title: "METRORail Security Team Expands by 40% for World Cup", author: "Laura Martinez", imageName: "Houston", fullText: "Houston's METRO has expanded its police and security personnel by 40% ahead of the World Cup. Officers will be a constant presence on all METRORail platforms and trains, particularly on the Red Line which serves NRG Park. In addition to uniformed officers, plainclothes units will be deployed to discreetly monitor for any illicit activities. The expansion is a proactive measure to manage the massive crowds expected and to ensure that public transportation remains a safe and reliable option for all fans traveling to and from the matches."),

        // Kansas City
        NewsArticle(city: "Kansas City", title: "KCPD Establishes Joint Command Post for Tournament", author: "James Anderson", imageName: "Kansas City", fullText: "The Kansas City Police Department has established a Joint Command Post near the Truman Sports Complex, integrating resources from local, state, and federal law enforcement. This central hub will coordinate all security operations for Arrowhead Stadium and the surrounding fan areas. Real-time intelligence sharing and synchronized deployment of assets will be key to managing the large-scale event. The KCPD has been planning this operation for over two years to ensure a seamless and secure environment for all attendees."),
        NewsArticle(city: "Kansas City", title: "Arrowhead Stadium Upgrades Entry Gates with New Scanners", author: "Robert Clark", imageName: "Kansas City", fullText: "Arrowhead Stadium has completed a major upgrade of its entry security infrastructure, installing new, high-throughput screening technology at all gates. This system is designed to process fans more quickly while providing a more thorough security check. The stadium has also reinforced its 'Clear Bag Policy,' reminding fans that only transparent bags of a specific size will be permitted inside. These measures are designed to enhance safety and improve the overall fan experience by reducing wait times at the gates."),
        NewsArticle(city: "Kansas City", title: "Enhanced Security Planned for Power & Light District", author: "Patricia Moore", imageName: "Kansas City", fullText: "With the Power & Light District designated as the official Fan Fest location, Kansas City officials have announced a robust security plan for the area. The entire district will have controlled entry points with bag checks on high-traffic match days. A heavy presence of private security and KCPD officers will be maintained throughout the tournament to ensure public safety. Organizers want to guarantee that the central entertainment hub remains a safe and enjoyable destination for families and fans from around the globe."),

        // Los Angeles
        NewsArticle(city: "Los Angeles", title: "LAPD Announces 'Safe LA' Initiative for World Cup", author: "Brian Thomas", imageName: "Los Angeles", fullText: "The Los Angeles Police Department has launched the 'Safe LA' initiative, a comprehensive security strategy for the World Cup. The plan involves deploying over 3,000 additional officers, establishing a city-wide surveillance network, and coordinating with multiple agencies, including the LA County Sheriff's Department. The focus will be on securing transportation hubs, tourist landmarks, and the areas around SoFi Stadium. The mayor has assured the public that the safety of residents and visitors is the city's absolute top priority during the global event."),
        NewsArticle(city: "Los Angeles", title: "SoFi Stadium to Operate 'Ring of Steel' Security Perimeter", author: "Michelle Rodriguez", imageName: "Los Angeles", fullText: "SoFi Stadium will be protected by a 'Ring of Steel' security perimeter, a multi-layered system of checkpoints and surveillance that begins far from the stadium itself. Vehicles will be subject to screening at outer checkpoints, and fans will pass through multiple layers of security before reaching the gates. This proven strategy, used at other major global events, is designed to prevent threats from ever reaching the immediate vicinity of the venue, ensuring the highest level of protection for everyone inside."),
        NewsArticle(city: "Los Angeles", title: "LA Metro to Deploy Visible and Undercover Security Teams", author: "Anthony Harris", imageName: "Los Angeles", fullText: "The LA Metro system will see a massive increase in security throughout the World Cup. Both uniformed and plainclothes security teams will be patrolling all trains and stations, with a particular focus on the K Line which directly serves the stadium in Inglewood. The Sheriff's Transit Services Bureau will be working extended hours, and K-9 units will be regularly sweeping major hubs like Union Station. These measures are intended to reassure the public and provide a secure transit experience for the millions of rides expected."),

        // Miami
        NewsArticle(city: "Miami", title: "Unified Command Structure to Secure Miami-Dade", author: "Maria Rodriguez", imageName: "Miami", fullText: "A unified command structure has been established in Miami-Dade County, bringing together city police, county police, and federal agencies like the Coast Guard and FBI. This integrated approach will ensure seamless security coverage from the beaches to the stadium. The command center will operate 24/7, monitoring everything from maritime traffic to social media for potential threats. This collaboration is crucial for managing an event of this magnitude in a major international tourist destination like Miami."),
        NewsArticle(city: "Miami", title: "Hard Rock Stadium Introduces Biometric Entry for Fans", author: "William Jackson", imageName: "Miami", fullText: "Hard Rock Stadium is offering an optional biometric entry system for fans to enhance both security and convenience. Registered fans can use a simple fingerprint or facial scan to enter the stadium, bypassing traditional ticket lines. This system not only speeds up the entry process but also provides a higher level of security by linking a ticket directly to an individual's unique biometric data. The stadium assures all data is encrypted and protected, offering a futuristic and secure way to access the games."),
        NewsArticle(city: "Miami", title: "Increased Police Presence and Lighting on South Beach", author: "Carlos Gomez", imageName: "Miami", fullText: "The City of Miami Beach Police Department has announced a significant increase in officer patrols and the installation of new, high-intensity lighting along Ocean Drive and the surrounding areas of South Beach. With fan parties expected to last late into the night, these measures are designed to deter crime and ensure a safe environment for everyone. Mounted patrols and bike units will be a common sight, providing a visible security presence and quick response capabilities in the crowded entertainment district."),

        // New York / New Jersey
        NewsArticle(city: "New York / New Jersey", title: "Massive Joint Task Force to Secure World Cup Final", author: "David Chen", imageName: "New York / New Jersey", fullText: "An unprecedented joint task force, involving over 50 local, state, and federal agencies, has been formed to secure the World Cup Final. Led by the FBI and the New Jersey State Police, the operation will be one of the largest security undertakings in the region's history. The plan involves air and maritime patrols, extensive surveillance, and thousands of officers dedicated to protecting MetLife Stadium and the surrounding infrastructure. Nothing is being left to chance for the world's most-watched sporting event."),
        NewsArticle(city: "New York / New Jersey", title: "MetLife Stadium Implements FAA Drone No-Fly Zone", author: "Rachel Green", imageName: "New York / New Jersey", fullText: "The Federal Aviation Administration (FAA) has designated the airspace over MetLife Stadium as a strict no-fly zone for drones during all World Cup matches. This restriction will be enforced by advanced counter-drone technology capable of detecting, tracking, and neutralizing unauthorized aircraft. State and federal law enforcement will be on-site to arrest any drone operators violating the temporary flight restriction. This measure is critical for ensuring the safety of players, spectators, and the integrity of the event."),
        NewsArticle(city: "New York / New Jersey", title: "NJ Transit and MTA Bolster Transportation Security", author: "Peter Jones", imageName: "New York / New Jersey", fullText: "NJ Transit and New York's MTA are collaborating on a comprehensive security plan for the vast public transportation network. This includes increased patrols by both NJ Transit Police and the NYPD on trains, buses, and in major hubs like Penn Station and Secaucus Junction. K-9 teams will conduct regular sweeps for explosives, and security checkpoints may be established at key stations during peak travel times on match days. The goal is to ensure millions of fans can travel safely and securely between New York City and the stadium."),
        
        // Philadelphia
        NewsArticle(city: "Philadelphia", title: "Philadelphia Announces 'Safe Corridors' for Fans", author: "Paul Wright", imageName: "Philadelphia", fullText: "The city has designated several 'Safe Corridors' for fans walking between Center City and the South Philadelphia Sports Complex. These routes will be clearly marked, well-lit, and will have a heavy and constant police presence. Mobile security cameras and information booths will be stationed along the corridors to assist visitors and deter any criminal activity. This initiative encourages fans to safely experience the city on foot while heading to the matches or fan zones, ensuring peace of mind for all."),
        NewsArticle(city: "Philadelphia", title: "Lincoln Financial Field to Use Mobile Security Towers", author: "Susan King", imageName: "Philadelphia", fullText: "To provide comprehensive surveillance of the large parking lots and tailgating areas, Lincoln Financial Field will deploy mobile security towers. These towers are equipped with multiple high-definition cameras and bright lighting, providing a 360-degree view that can be monitored from the central command post. Their mobility allows security to position them in strategic locations based on crowd patterns and intelligence, offering a flexible and powerful tool to enhance the safety of the stadium's exterior spaces."),
        NewsArticle(city: "Philadelphia", title: "SEPTA Transit Police to Escort Fan Groups", author: "George Hill", imageName: "Philadelphia", fullText: "The SEPTA Transit Police will be implementing a new program to escort large fan groups traveling on the Broad Street Line. On match days, officers will ride in the subway cars with major supporter groups to ensure orderly conduct and prevent any potential conflicts. This visible presence is designed to provide a deterrent to disruptive behavior and offer a sense of security to all passengers. It's part of a broader strategy to make public transit the safest and most efficient way to travel to the stadium."),
        
        // San Francisco Bay Area
        NewsArticle(city: "San Francisco Bay Area", title: "Bay Area Security Plan Spans Multiple Cities", author: "Nancy Allen", imageName: "San Francisco Bay Area", fullText: "A regional security plan has been announced for the Bay Area, coordinating law enforcement from San Jose, Santa Clara, and San Francisco. A central command hub will manage resources across the entire area, focusing on Levi's Stadium, transportation corridors like Caltrain, and major fan gathering spots. This unified approach is essential for an event spread across a large and populous metropolitan region, ensuring consistent security protocols and rapid response capabilities wherever fans may be."),
        NewsArticle(city: "San Francisco Bay Area", title: "Levi's Stadium Enhances Cybersecurity Measures", author: "Mark Young", imageName: "San Francisco Bay Area", fullText: "Recognizing its location in the heart of Silicon Valley, Levi's Stadium has implemented cutting-edge cybersecurity measures to protect its network infrastructure. This includes protecting the stadium's public Wi-Fi, ticketing systems, and operational controls from potential cyberattacks. A team of cybersecurity experts will be on-site 24/7 to monitor for threats and ensure the digital safety of the venue and its visitors, safeguarding personal data and preventing any technologically-driven disruptions."),
        NewsArticle(city: "San Francisco Bay Area", title: "Caltrain and VTA to Have Onboard Security Teams", author: "Barbara Scott", imageName: "San Francisco Bay Area", fullText: "Both Caltrain and the VTA light rail system will have dedicated security teams onboard every train during World Cup match days. These teams, consisting of transit police and private security, will provide a visible deterrent and be available to immediately address any safety concerns from passengers. The enhanced presence is a key component of the transportation plan, designed to give fans confidence in using public transit to travel to and from Levi's Stadium in Santa Clara from all over the Bay Area."),
        
        // Seattle
        NewsArticle(city: "Seattle", title: "Seattle Police Coordinate with Port and Maritime Security", author: "Steven Adams", imageName: "Seattle", fullText: "Given its unique geography, the Seattle Police Department is coordinating closely with the Port of Seattle Police and the U.S. Coast Guard. A comprehensive maritime security plan will be in effect, with increased patrols around the downtown waterfront and near the stadium. This includes monitoring ferry traffic and recreational boaters to ensure the safety of the city's vital waterways during the high-profile event. The plan addresses both land and sea-based security concerns in an integrated fashion."),
        NewsArticle(city: "Seattle", title: "Lumen Field Installs New Threat Detection System", author: "Donna Baker", imageName: "Seattle", fullText: "Lumen Field has installed a new, state-of-the-art threat detection system at all entrances. This technology uses advanced sensors to screen for a wide range of prohibited items without requiring fans to stop and be wanded individually. This will dramatically improve the flow of fans into the stadium while providing a higher level of security screening. The stadium is one of the first in the country to adopt this specific system, prioritizing both safety and the fan experience for the World Cup."),
        NewsArticle(city: "Seattle", title: "Sound Transit to Increase Security on Link Light Rail", author: "Charles Nelson", imageName: "Seattle", fullText: "Sound Transit has announced a major increase in security personnel across the Link light rail system. Security officers will be present at every station and on every train, especially on the lines serving the Stadium and International District stations. This heightened visibility is intended to ensure a safe and orderly environment for the tens of thousands of fans expected to use the light rail to get to matches. The 'Safe Rider' program will also be promoted, encouraging passengers to report any issues directly to staff."),
        
        // MARK: - CANADA CITIES (2)
        
        // Toronto
        NewsArticle(city: "Toronto", title: "Toronto Police Service Announces 'Safe TO' Security Plan", author: "Sarah Jenkins", imageName: "Toronto", fullText: "The Toronto Police Service has launched 'Safe TO,' its official security plan for the World Cup. The strategy involves a significant increase in officer presence in the downtown core, at fan zones, and around BMO Field. The plan also includes a public awareness campaign about personal safety and how to report suspicious activity. A dedicated, multilingual visitor support hotline will be active 24/7 to assist tourists with any safety concerns they may have during their stay in the city."),
        NewsArticle(city: "Toronto", title: "BMO Field Perimeter to Feature 'Intelligent' Fencing", author: "Li Wang", imageName: "Toronto", fullText: "The expanded perimeter around BMO Field will feature 'intelligent' fencing equipped with sensors and cameras. This technology can detect climbing, cutting, or tampering and will automatically alert the security command center with a live video feed of the specific location. This allows for a rapid response to any potential breaches of the stadium's outer security layer. It's a proactive measure designed to secure the venue long before anyone reaches the entry gates."),
        NewsArticle(city: "Toronto", title: "GO Transit and TTC to Deploy Special Constables", author: "Tom Gordon", imageName: "Toronto", fullText: "Both GO Transit and the Toronto Transit Commission (TTC) will deploy their full force of Special Constables during the tournament. These officers will have a high-visibility presence at major hubs like Union Station and on all routes serving Exhibition Place. Their focus will be on crowd management and ensuring passenger safety. This coordinated effort between the two major transit agencies is vital for securing the movement of millions of people throughout the Greater Toronto Area."),
        
        // Vancouver
        NewsArticle(city: "Vancouver", title: "Vancouver Adopts 'Integrated Security Unit' Model", author: "Emily Carr", imageName: "Vancouver", fullText: "Following the model of previous major events in the city, Vancouver will establish an Integrated Security Unit (ISU) for the World Cup. This unit brings officers from the Vancouver Police Department, the RCMP, and other agencies under a single, unified command structure. The ISU will be responsible for all aspects of tournament security, from stadium operations to protecting public fan zones, ensuring a coordinated and effective response to any situation that may arise."),
        NewsArticle(city: "Vancouver", title: "BC Place to Enforce 100% Bag Screening Policy", author: "Mike O'Brian", imageName: "Vancouver", fullText: "BC Place has confirmed that a 100% screening policy will be in effect for all bags entering the stadium. While clear bags are strongly encouraged to speed up entry, all bags will be subject to a thorough physical search by security personnel. This strict policy is in place to prevent any prohibited items from entering the venue. Multiple screening lanes will be set up to manage the process as efficiently as possible, and fans are advised to arrive early to avoid delays."),
        NewsArticle(city: "Vancouver", title: "SkyTrain Stations to Feature Enhanced Surveillance", author: "Chloe Kim", imageName: "Vancouver", fullText: "All SkyTrain stations, especially those on the Expo Line serving BC Place, will feature enhanced surveillance and an increased presence of Transit Police. TransLink is upgrading many of its station cameras to high-definition models and will have staff actively monitoring feeds in real-time. The goal is to create a secure transit environment where fans feel safe traveling to and from the matches, knowing that the system is being closely watched to prevent any incidents."),
        
        // MARK: - MEXICO CITIES (3)
        
        // Guadalajara
        NewsArticle(city: "Guadalajara", title: "Jalisco State Police to Lead Regional Security Effort", author: "Ana Cruz", imageName: "Guadalajara", fullText: "The Jalisco State Police will take the lead in a regional security effort, coordinating with municipal police from Guadalajara, Zapopan, and Tlaquepaque. This joint operation will ensure consistent security coverage across the entire metropolitan area. Over 5,000 officers will be dedicated to World Cup duties, focusing on protecting hotels, tourist areas, and the routes leading to Estadio Akron. Federal forces will also be on hand to provide additional support and intelligence capabilities."),
        NewsArticle(city: "Guadalajara", title: "Estadio Akron Implements Triple-Check Security Zone", author: "Javier Solis", imageName: "Guadalajara", fullText: "A triple-check security zone will be established around Estadio Akron on match days. The first checkpoint will screen vehicles far from the stadium. The second will be a ticket and credential check for pedestrians. The final checkpoint at the stadium gates will involve a full personal and bag screening. This layered approach is designed to filter out any potential threats long before they can get near the venue, creating a secure bubble for fans to enjoy the matches."),
        NewsArticle(city: "Guadalajara", title: "Tourist Police to Patrol Historic Downtown", author: "Elena Fuentes", imageName: "Guadalajara", fullText: "A special unit of the Tourist Police, with bilingual officers, will be deployed throughout Guadalajara's historic downtown. These officers are specifically trained to assist international visitors, providing directions, information, and a sense of security. They will be easily identifiable and stationed near key landmarks such as the cathedral, Plaza de Armas, and Hospicio Cabañas. Their presence is aimed at ensuring all visitors have a safe and pleasant experience while exploring the city's rich culture."),

        // Mexico City
        NewsArticle(city: "Mexico City", title: "Secretariat of Citizen Security Deploys 10,000 Officers", author: "Lalo Cardenas", imageName: "Mexico City", fullText: "Mexico City's Secretariat of Citizen Security (SSC) has announced the deployment of 10,000 police officers specifically for World Cup security. This massive operation will involve officers from traffic, tourist, and special operations units. Their primary focus will be on securing Estadio Azteca, the Zócalo fan fest, and key transportation hubs like the airport and major metro stations. This represents one of the largest security deployments in the city's recent history."),
        NewsArticle(city: "Mexico City", title: "Estadio Azteca to Use Facial Recognition Technology", author: "Sofia Reyes", imageName: "Mexico City", fullText: "As part of its major renovation, Estadio Azteca is installing a new facial recognition system at all entrances. This technology will be used to identify individuals who are on security watchlists or have been previously banned from sporting events. While optional for most fans, the system adds a powerful layer of security to prevent known troublemakers from entering the stadium. Officials have stressed that the data will be handled in accordance with privacy laws and used exclusively for security purposes."),
        NewsArticle(city: "Mexico City", title: "National Guard to Secure Metro 'Football Lines'", author: "Ricardo Morales", imageName: "Mexico City", fullText: "The Mexican National Guard will be assisting with security along the city's Metro system, with a particular focus on the special 'Football Lines' serving Estadio Azteca. Soldiers will be stationed at key transfer points and at the stadium station to manage crowds and provide a visible security presence. This collaboration between city police and federal forces is designed to ensure the safe and orderly transport of millions of fans who will rely on the Metro to get to the historic venue."),

        // Monterrey
        NewsArticle(city: "Monterrey", title: "Fuerza Civil Announces 'Safe Stadium' Operation", author: "Miguel Garza", imageName: "Monterrey", fullText: "Nuevo León's state police force, Fuerza Civil, has announced its 'Safe Stadium' operation for the World Cup. The plan involves creating a secure perimeter around Estadio BBVA and managing traffic flow on the surrounding highways. State helicopters will provide aerial surveillance on match days, and special units will be on standby to respond to any major incidents. The governor has stated that ensuring a safe and family-friendly atmosphere is the state's top priority."),
        NewsArticle(city: "Monterrey", title: "Estadio BBVA to Enforce Fan ID for Entry", author: "Isabella Garza", imageName: "Monterrey", fullText: "In addition to a match ticket, all fans entering Estadio BBVA will be required to present a registered Fan ID. This system, which has been used successfully in Liga MX, links a ticket to a specific, identified person, helping to prevent ticket fraud and track anyone involved in misconduct. Registration for the Fan ID must be completed online before arriving at the stadium. This measure is a key part of the effort to eliminate violence and unruly behavior from football stadiums."),
        NewsArticle(city: "Monterrey", title: "Security Increased in Parque Fundidora Fan Zone", author: "Pedro Ramirez", imageName: "Monterrey", fullText: "A robust security plan is in place for the official fan zone at Parque Fundidora. The park will have controlled access points with metal detectors and bag checks. Both private security and officers from Fuerza Civil will patrol the grounds to ensure a safe environment for the tens of thousands of fans expected to gather there. The extensive and open nature of the park presents unique security challenges, which officials say they are fully prepared to handle throughout the tournament.")
    ]
}

