//
//  NewModel.swift (Modelo de Noticias)
//  SafeFun
//
//  Created by Facultad de Contaduría y Administración on 21/10/25.
//
import SwiftUI

struct NewsArticle: Identifiable {
    let id: UUID
    let city: String
    let title: String
    let publishDate: Date
    let author: String
    let imageName: String
    let fullText: String
    
    init(city: String, title: String, publishDate: Date = Date(), author: String, imageName: String, fullText: String) {
        self.id = UUID()
        self.city = city
        self.title = title
        self.publishDate = publishDate
        self.author = author
        self.imageName = imageName
        self.fullText = fullText
    }
}

// --- BASE DE DATOS DE PRUEBA (MOCK) ---
extension NewsArticle {
    static let allNewsArticles: [NewsArticle] = [
        // MARK: - CIUDADES DE EE.UU. (11)
        
        // Atlanta
        NewsArticle(city: "Atlanta", title: "Policía de Atlanta Anuncia Red de Seguridad para Toda la Ciudad", author: "Maria Garcia", imageName: "Atlanta", fullText: "El Departamento de Policía de Atlanta, en colaboración con socios federales, ha anunciado una red de seguridad integral para toda la ciudad para garantizar la seguridad de todos los residentes y visitantes durante la Copa del Mundo. Esta estrategia de múltiples capas incluye un aumento de patrullas en áreas de alto tráfico como el centro, Midtown y las áreas que rodean el Estadio Mercedes-Benz. Se desplegarán más de 2,000 oficiales adicionales, con unidades especializadas enfocadas en contraterrorismo, gestión del tráfico y orden público. Los centros de comando monitorearán una red de más de 15,000 cámaras de CCTV 24/7."),
        
        NewsArticle(city: "Atlanta", title: "Estadio Mercedes-Benz Despliega Detección con IA", author: "John Smith", imageName: "Atlanta", fullText: "El Estadio Mercedes-Benz está estableciendo un nuevo estándar para la seguridad de recintos con la implementación de un sistema avanzado de detección impulsado por IA. Esta tecnología sin contacto permite a los fanáticos ingresar al estadio sin sacar artículos de sus bolsillos o bolsos, acelerando significativamente los tiempos de entrada mientras mejora la detección de amenazas. El sistema puede distinguir entre artículos cotidianos como teléfonos y llaves y artículos prohibidos, marcando posibles preocupaciones para una segunda revisión. Los funcionarios afirman que esto creará una experiencia más segura y fluida para los cientos de miles de fanáticos que asistan a los partidos."),

        NewsArticle(city: "Atlanta", title: "MARTA Refuerza la Seguridad del Tránsito para el Torneo", author: "Emily White", imageName: "Atlanta", fullText: "La Autoridad de Tránsito Rápido Metropolitano de Atlanta (MARTA) ha reforzado sus medidas de seguridad en todas las líneas de tren y autobús. Los viajeros notarán un aumento significativo de oficiales uniformados y unidades K-9 patrullando estaciones y vehículos. Además de la seguridad visible, MARTA ha actualizado sus sistemas de vigilancia con cámaras de mayor resolución y capacidades de monitoreo en tiempo real conectadas directamente al comando central de la policía. Estos esfuerzos están diseñados para proporcionar una opción de transporte segura y confiable para los fanáticos que viajan a los partidos y otros eventos de la ciudad durante la Copa del Mundo."),

        // Boston
        NewsArticle(city: "Boston", title: "Fuerza de Tarea Multiagencia Asegurará Zonas de Fans en Boston", author: "Chris Lee", imageName: "Boston", fullText: "Se ha establecido una fuerza de tarea multiagencia que incluye al Departamento de Policía de Boston, la Policía Estatal de Massachusetts y el FBI para supervisar la seguridad en todas las zonas de fans oficiales. Estas zonas, ubicadas en City Hall Plaza y el Seaport, contarán con cercas perimetrales, revisiones de bolsos y una fuerte presencia policial. También se desplegarán oficiales encubiertos para monitorear a las multitudes e identificar cualquier posible disturbio. El objetivo es crear un ambiente familiar y seguro donde los fanáticos puedan disfrutar de los partidos en pantallas gigantes y participar en las festividades sin preocupaciones."),


        NewsArticle(city: "Boston", title: "Gillette Stadium Aplica Estricta Política de No Bolsos", author: "David Chen", imageName: "Boston", fullText: "El Gillette Stadium ha anunciado una estricta política de no bolsos para todos los partidos de la Copa del Mundo para mejorar la seguridad y agilizar la entrada. Solo se permitirán bolsos de mano pequeños, no más grandes que una mano. Todos los demás bolsos, incluidas mochilas y carteras, están estrictamente prohibidos. Se alienta a los fanáticos a empacar ligero y utilizar los casilleros que estarán disponibles para alquilar cerca de las entradas del estadio. Esta política, común en la NFL, se adopta para minimizar amenazas potenciales y crear un entorno más seguro dentro del recinto para todos los asistentes."),

        NewsArticle(city: "Boston", title: "MBTA Aumenta Patrullas en Líneas de Tren de Cercanías", author: "Jessica Miller", imageName: "Boston", fullText: "La MBTA ha aumentado significativamente su presencia de seguridad en todas las líneas de Tren de Cercanías, particularmente en la Línea Providence/Stoughton que sirve al Gillette Stadium. La Policía de Tránsito realizará revisiones aleatorias de bolsos y tendrá un mayor número de oficiales viajando en los trenes los días de partido. Se promoverá fuertemente la campaña 'Si ves algo, di algo', con instrucciones claras sobre cómo informar discretamente actividades sospechosas a las autoridades utilizando la aplicación de seguridad dedicada de la MBTA."),

        // Dallas
        NewsArticle(city: "Dallas", title: "Centro de Comando de Dallas Integra Seguridad Regional", author: "Michael Brown", imageName: "Dallas", fullText: "La Ciudad de Dallas ha activado un Centro de Operaciones Conjuntas (JOC) de última generación que integra transmisiones y comunicaciones de los departamentos de policía de todo el Metroplex, incluidos Arlington y Fort Worth. Este centro de comando centralizado permitirá la coordinación en tiempo real de los activos de seguridad, la gestión del tráfico y la respuesta a emergencias. Agencias federales como el Departamento de Seguridad Nacional también tendrán presencia en el JOC para proporcionar inteligencia y apoyo durante el torneo, asegurando un frente de seguridad unificado en toda la región."),
        
        NewsArticle(city: "Dallas", title: "AT&T Stadium Usará Vigilancia con Drones para Seguridad Perimetral", author: "Jennifer Davis", imageName: "Dallas", fullText: "El AT&T Stadium desplegará una flota de drones de seguridad para monitorear el extenso perímetro y los estacionamientos durante los días de partido. Estos drones están equipados con cámaras térmicas y de alta resolución, proporcionando al personal de seguridad una vista aérea de todo el complejo. El sistema está diseñado para detectar drones no autorizados, identificar actividades sospechosas en tiempo real y ayudar a gestionar el flujo de multitudes antes y después de los partidos. Esta medida de vigilancia proactiva es parte de una cobertura de seguridad de alta tecnología diseñada para proteger uno de los recintos deportivos más grandes del mundo."),

        NewsArticle(city: "Dallas", title: "DART Light Rail Aumenta Revisiones de Seguridad en Estaciones", author: "Kevin Wilson", imageName: "Dallas", fullText: "Dallas Area Rapid Transit (DART) implementará mayores protocolos de seguridad en todo su sistema de tren ligero. Los fanáticos que viajen a Fair Park y otras ubicaciones centrales encontrarán una mayor visibilidad de los oficiales de policía de DART y de los funcionarios de control de tarifas. Unidades K-9 entrenadas en detección de explosivos realizarán barridos en estaciones clave, incluida la Estación Victory y las líneas que sirven al estadio. DART se compromete a mantener un entorno de tránsito seguro y eficiente para los millones de visitantes que se espera que utilicen el sistema."),

        // Houston
        NewsArticle(city: "Houston", title: "Policía de Houston Presenta Programa 'Zonas de Seguridad Turística'", author: "Sarah Johnson", imageName: "Houston", fullText: "La Policía de Houston ha designado varias 'Zonas de Seguridad Turística' en áreas de alto tráfico como The Galleria, el Distrito de Museos y el Centro. Estas zonas contarán con una mayor presencia de oficiales, quioscos de información móviles con personal multilingüe e iluminación mejorada. La iniciativa está diseñada para proporcionar a los visitantes áreas seguras y acogedoras para explorar las atracciones de la ciudad. Una línea directa dedicada y una función en la aplicación permitirán a los turistas informar rápidamente cualquier inquietud y recibir asistencia inmediata, asegurando una experiencia positiva y segura en Houston."),

        NewsArticle(city: "Houston", title: "NRG Stadium Implementa Sistema Avanzado de Credenciales", author: "Daniel Taylor", imageName: "Houston", fullText: "Se está implementando un nuevo sistema de credenciales digitales en el NRG Stadium para todo el personal, medios y jugadores para mejorar la seguridad del control de acceso. El sistema utiliza datos biométricos para verificar identidades, evitando el acceso no autorizado a áreas restringidas. Esta tecnología asegura que solo las personas investigadas y aprobadas puedan ingresar a zonas sensibles como vestuarios y puestos de comando operativo. Representa una mejora significativa con respecto a los pases laminados tradicionales y es una parte clave del plan de seguridad integral del recinto para proteger la integridad del evento."),

        NewsArticle(city: "Houston", title: "Equipo de Seguridad de METRORail se Expande un 40% para la Copa del Mundo", author: "Laura Martinez", imageName: "Houston", fullText: "METRO de Houston ha expandido su personal de policía y seguridad en un 40% antes de la Copa del Mundo. Los oficiales serán una presencia constante en todas las plataformas y trenes de METRORail, particularmente en la Línea Roja que sirve al NRG Park. Además de los oficiales uniformados, se desplegarán unidades de civil para monitorear discretamente cualquier actividad ilícita. La expansión es una medida proactiva para gestionar las multitudes masivas que se esperan y para garantizar que el transporte público siga siendo una opción segura y confiable para todos los fanáticos que viajan hacia y desde los partidos."),

        // Kansas City
        NewsArticle(city: "Kansas City", title: "KCPD Establece Puesto de Comando Conjunto para el Torneo", author: "James Anderson", imageName: "Kansas City", fullText: "El Departamento de Policía de Kansas City ha establecido un Puesto de Comando Conjunto cerca del Complejo Deportivo Truman, integrando recursos de las fuerzas del orden locales, estatales y federales. Este centro neurálgico coordinará todas las operaciones de seguridad para el Estadio Arrowhead y las áreas de fans circundantes. El intercambio de inteligencia en tiempo real y el despliegue sincronizado de activos serán clave para gestionar el evento a gran escala. El KCPD ha estado planeando esta operación durante más de dos años para garantizar un entorno fluido y seguro para todos los asistentes."),

        NewsArticle(city: "Kansas City", title: "Arrowhead Stadium Actualiza Puertas de Entrada con Nuevos Escáneres", author: "Robert Clark", imageName: "Kansas City", fullText: "El Estadio Arrowhead ha completado una importante actualización de su infraestructura de seguridad de entrada, instalando nueva tecnología de escaneo de alto rendimiento en todas las puertas. Este sistema está diseñado para procesar a los fanáticos más rápidamente mientras proporciona una revisión de seguridad más exhaustiva. El estadio también ha reforzado su 'Política de Bolsa Transparente', recordando a los fanáticos que solo se permitirán bolsas transparentes de un tamaño específico en el interior. Estas medidas están diseñadas para mejorar la seguridad y la experiencia general del fan al reducir los tiempos de espera en las puertas."),

        NewsArticle(city: "Kansas City", title: "Seguridad Reforzada Planeada para el Distrito Power & Light", author: "Patricia Moore", imageName: "Kansas City", fullText: "Con el Distrito Power & Light designado como la ubicación oficial del Fan Fest, los funcionarios de Kansas City han anunciado un sólido plan de seguridad para el área. Todo el distrito tendrá puntos de entrada controlados con revisiones de bolsos en los días de partido de alto tráfico. Se mantendrá una fuerte presencia de seguridad privada y oficiales del KCPD durante todo el torneo para garantizar la seguridad pública. Los organizadores quieren garantizar que el centro de entretenimiento principal siga siendo un destino seguro y agradable para familias y fanáticos de todo el mundo."),

        // Los Angeles
        NewsArticle(city: "Los Angeles", title: "LAPD Anuncia Iniciativa 'Safe LA' para la Copa del Mundo", author: "Brian Thomas", imageName: "Los Angeles", fullText: "El Departamento de Policía de Los Ángeles ha lanzado la iniciativa 'Safe LA', una estrategia de seguridad integral para la Copa del Mundo. El plan implica desplegar más de 3,000 oficiales adicionales, establecer una red de vigilancia en toda la ciudad y coordinarse con múltiples agencias, incluido el Departamento del Sheriff del Condado de LA. El enfoque estará en asegurar los centros de transporte, los puntos de referencia turísticos y las áreas alrededor del SoFi Stadium. El alcalde ha asegurado al público que la seguridad de los residentes y visitantes es la máxima prioridad de la ciudad durante el evento global."),

        NewsArticle(city: "Los Angeles", title: "SoFi Stadium Operará Perímetro de Seguridad 'Anillo de Acero'", author: "Michelle Rodriguez", imageName: "Los Angeles", fullText: "El SoFi Stadium estará protegido por un perímetro de seguridad de 'Anillo de Acero', un sistema de múltiples capas de puntos de control y vigilancia que comienza lejos del estadio mismo. Los vehículos estarán sujetos a revisión en puntos de control exteriores, y los fanáticos pasarán por múltiples capas de seguridad antes de llegar a las puertas. Esta estrategia probada, utilizada en otros eventos globales importantes, está diseñada para evitar que las amenazas lleguen a las inmediaciones del recinto, garantizando el más alto nivel de protección para todos los que están dentro."),
        
        NewsArticle(city: "Los Angeles", title: "Metro de LA Desplegará Equipos de Seguridad Visibles y Encubiertos", author: "Anthony Harris", imageName: "Los Angeles", fullText: "El sistema de Metro de LA verá un aumento masivo en la seguridad durante la Copa del Mundo. Equipos de seguridad tanto uniformados como de civil patrullarán todos los trenes y estaciones, con un enfoque particular en la Línea K que sirve directamente al estadio en Inglewood. La Oficina de Servicios de Tránsito del Sheriff trabajará en horarios extendidos, y unidades K-9 realizarán barridos regulares en los principales centros como Union Station. Estas medidas están destinadas a tranquilizar al público y proporcionar una experiencia de tránsito segura para los millones de viajes esperados."),

        // Miami
        NewsArticle(city: "Miami", title: "Estructura de Comando Unificado Asegurará Miami-Dade", author: "Maria Rodriguez", imageName: "Miami", fullText: "Se ha establecido una estructura de comando unificado en el condado de Miami-Dade, que reúne a la policía de la ciudad, la policía del condado y agencias federales como la Guardia Costera y el FBI. Este enfoque integrado garantizará una cobertura de seguridad fluida desde las playas hasta el estadio. El centro de comando operará 24/7, monitoreando todo, desde el tráfico marítimo hasta las redes sociales en busca de amenazas potenciales. Esta colaboración es crucial para gestionar un evento de esta magnitud en un importante destino turístico internacional como Miami."),

        NewsArticle(city: "Miami", title: "Hard Rock Stadium Introduce Entrada Biométrica para Fans", author: "William Jackson", imageName: "Miami", fullText: "El Hard Rock Stadium ofrece un sistema de entrada biométrica opcional para los fanáticos para mejorar tanto la seguridad como la comodidad. Los fanáticos registrados pueden usar una simple huella digital o escaneo facial para ingresar al estadio, evitando las filas de boletos tradicionales. Este sistema no solo acelera el proceso de entrada, sino que también proporciona un mayor nivel de seguridad al vincular un boleto directamente con los datos biométricos únicos de un individuo. El estadio asegura que todos los datos están encriptados y protegidos, ofreciendo una forma futurista y segura de acceder a los juegos."),

        NewsArticle(city: "Miami", title: "Aumento de Presencia Policial e Iluminación en South Beach", author: "Carlos Gomez", imageName: "Miami", fullText: "El Departamento de Policía de Miami Beach ha anunciado un aumento significativo en las patrullas de oficiales y la instalación de nueva iluminación de alta intensidad a lo largo de Ocean Drive y las áreas circundantes de South Beach. Dado que se espera que las fiestas de los fanáticos duren hasta altas horas de la noche, estas medidas están diseñadas para disuadir el crimen y garantizar un entorno seguro para todos. Las patrullas montadas y las unidades de bicicletas serán vistas comúnmente, proporcionando una presencia de seguridad visible y capacidades de respuesta rápida en el concurrido distrito de entretenimiento."),

        // New York

        NewsArticle(city: "New York", title: "Fuerza de Tarea Conjunta Masiva Asegurará la Final de la Copa del Mundo", author: "David Chen", imageName: "New York", fullText: "Se ha formado una fuerza de tarea conjunta sin precedentes, que involucra a más de 50 agencias locales, estatales y federales, para asegurar la Final de la Copa del Mundo. Liderada por el FBI y la Policía Estatal de Nueva Jersey, la operación será uno de los mayores operativos de seguridad en la historia de la región. El plan incluye patrullas aéreas y marítimas, vigilancia extensa y miles de oficiales dedicados a proteger el MetLife Stadium y la infraestructura circundante. No se deja nada al azar para el evento deportivo más visto del mundo."),

        NewsArticle(city: "New York", title: "MetLife Stadium Implementa Zona de Exclusión Aérea de Drones de la FAA", author: "Rachel Green", imageName: "New York", fullText: "La Administración Federal de Aviación (FAA) ha designado el espacio áereo sobre el MetLife Stadium como una estricta zona de exclusión aérea para drones durante todos los partidos de la Copa del Mundo. Esta restricción será aplicada por tecnología antidrones avanzada capaz de detectar, rastrear y neutralizar aeronaves no autorizadas. Las fuerzas del orden estatales y federales estarán en el lugar para arrestar a cualquier operador de drones que viole la restricción de vuelo temporal. Esta medida es crítica para garantizar la seguridad de los jugadores, espectadores y la integridad del evento."),

        NewsArticle(city: "New York", title: "NJ Transit y MTA Refuerzan la Seguridad del Transporte", author: "Peter Jones", imageName: "New York", fullText: "NJ Transit y la MTA de Nueva York están colaborando en un plan de seguridad integral para la vasta red de transporte público. Esto incluye un aumento de patrullas tanto de la Policía de NJ Transit como del NYPD en trenes, autobuses y en los principales centros como Penn Station y Secaucus Junction. Equipos K-9 realizarán barridos regulares en busca de explosivos, y se podrán establecer puntos de control de seguridad en estaciones clave durante las horas pico de viaje en los días de partido. El objetivo es garantizar que millones de fanáticos puedan viajar de manera segura entre la ciudad de Nueva York y el estadio."),

        // Philadelphia
        NewsArticle(city: "Philadelphia", title: "Filadelfia Anuncia 'Corredores Seguros' para Fans", author: "Paul Wright", imageName: "Philadelphia", fullText: "La ciudad ha designado varios 'Corredores Seguros' para los fanáticos que caminan entre el Center City y el Complejo Deportivo del Sur de Filadelfia. Estas rutas estarán claramente marcadas, bien iluminadas y tendrán una presencia policial fuerte y constante. Cámaras de seguridad móviles y puestos de información estarán estacionados a lo largo de los corredores para ayudar a los visitantes y disuadir cualquier actividad criminal. Esta iniciativa alienta a los fanáticos a experimentar la ciudad de manera segura a pie mientras se dirigen a los partidos o zonas de fans, garantizando la tranquilidad de todos."),

        NewsArticle(city: "Philadelphia", title: "Lincoln Financial Field Usará Torres de Seguridad Móviles", author: "Susan King", imageName: "Philadelphia", fullText: "Para proporcionar una vigilancia integral de los grandes estacionamientos y áreas de 'tailgating', el Lincoln Financial Field desplegará torres de seguridad móviles. Estas torres están equipadas con múltiples cámaras de alta definición e iluminación brillante, proporcionando una vista de 360 grados que se puede monitorear desde el puesto de comando central. Su movilidad permite a la seguridad posicionarlas en ubicaciones estratégicas según los patrones de la multitud y la inteligencia, ofreciendo una herramienta flexible y poderosa para mejorar la seguridad de los espacios exteriores del estadio."),

        NewsArticle(city: "Philadelphia", title: "Policía de Tránsito de SEPTA Escoltará a Grupos de Fans", author: "George Hill", imageName: "Philadelphia", fullText: "La Policía de Tránsito de SEPTA implementará un nuevo programa para escoltar a grandes grupos de fanáticos que viajen en la Línea de Broad Street. En los días de partido, los oficiales viajarán en los vagones del metro con los principales grupos de seguidores para garantizar una conducta ordenada y prevenir cualquier conflicto potencial. Esta presencia visible está diseñada para disuadir el comportamiento disruptivo y ofrecer una sensación de seguridad a todos los pasajeros. Es parte de una estrategia más amplia para hacer del transporte público la forma más segura y eficiente de viajar al estadio."),

        // San Francisco
        NewsArticle(city: "San Francisco", title: "Plan de Seguridad del Área de la Bahía Abarca Múltiples Ciudades", author: "Nancy Allen", imageName: "San Francisco", fullText: "Se ha anunciado un plan de seguridad regional para el Área de la Bahía, coordinando a las fuerzas del orden de San José, Santa Clara y San Francisco. Un centro de comando central gestionará los recursos en toda el área, centrándose en el Levi's Stadium, los corredores de transporte como Caltrain y los principales puntos de reunión de fanáticos. Este enfoque unificado es esencial para un evento distribuido en una región metropolitana grande y poblada, asegurando protocolos de seguridad consistentes y capacidades de respuesta rápida dondequiera que estén los fanáticos."),
        
        NewsArticle(city: "San Francisco", title: "Levi's Stadium Refuerza Medidas de Ciberseguridad", author: "Mark Young", imageName: "San Francisco", fullText: "Reconociendo su ubicación en el corazón de Silicon Valley, el Levi's Stadium ha implementado medidas de ciberseguridad de vanguardia para proteger su infraestructura de red. Esto incluye la protección del Wi-Fi público del estadio, los sistemas de venta de boletos y los controles operativos contra posibles ciberataques. Un equipo de expertos en ciberseguridad estará en el lugar 24/7 para monitorear amenazas y garantizar la seguridad digital del recinto y sus visitantes, salvaguardando los datos personales y previniendo cualquier interrupción impulsada por la tecnología."),

        NewsArticle(city: "San Francisco", title: "Caltrain y VTA Tendrán Equipos de Seguridad a Bordo", author: "Barbara Scott", imageName: "San Francisco", fullText: "Tanto Caltrain como el sistema de tren ligero VTA tendrán equipos de seguridad dedicados a bordo de cada tren durante los días de partido de la Copa del Mundo. Estos equipos, compuestos por policía de tránsito y seguridad privada, proporcionarán un elemento disuasorio visible y estarán disponibles para abordar de inmediato cualquier inquietud de seguridad de los pasajeros. La presencia mejorada es un componente clave del plan de transporte, diseñado para dar a los fanáticos confianza al usar el transporte público para viajar hacia y desde el Levi's Stadium en Santa Clara desde toda el Área de la Bahía."),

        // Seattle
        NewsArticle(city: "Seattle", title: "Policía de Seattle se Coordina con Seguridad Portuaria y Marítima", author: "Steven Adams", imageName: "Seattle", fullText: "Dada su geografía única, el Departamento de Policía de Seattle está coordinando estrechamente con la Policía del Puerto de Seattle y la Guardia Costera de EE. UU. Se implementará un plan integral de seguridad marítima, con un aumento de patrullas alrededor del muelle del centro y cerca del estadio. Esto incluye monitorear el tráfico de ferris y navegantes recreativos para garantizar la seguridad de las vías fluviales vitales de la ciudad durante el evento de alto perfil. El plan aborda las preocupaciones de seguridad tanto terrestres como marítimas de manera integrada."),

        NewsArticle(city: "Seattle", title: "Lumen Field Instala Nuevo Sistema de Detección de Amenazas", author: "Donna Baker", imageName: "Seattle", fullText: "Lumen Field ha instalado un nuevo sistema de detección de amenazas de última generación en todas las entradas. Esta tecnología utiliza sensores avanzados para detectar una amplia gama de artículos prohibidos sin requerir que los fanáticos se detengan y sean revisados individualmente. Esto mejorará drásticamente el flujo de fanáticos hacia el estadio al tiempo que proporciona un nivel más alto de control de seguridad. El estadio es uno de los primeros en el país en adoptar este sistema específico, priorizando tanto la seguridad como la experiencia del fan para la Copa del Mundo."),

        NewsArticle(city: "Seattle", title: "Sound Transit Aumentará la Seguridad en el Link Light Rail", author: "Charles Nelson", imageName: "Seattle", fullText: "Sound Transit ha anunciado un importante aumento de personal de seguridad en todo el sistema Link light rail. Habrá oficiales de seguridad presentes en cada estación y en cada tren, especialmente en las líneas que sirven a las estaciones Stadium e International District. Esta visibilidad aumentada tiene como objetivo garantizar un entorno seguro y ordenado para las decenas de miles de fanáticos que se espera que utilicen el tren ligero para llegar a los partidos. También se promoverá el programa 'Safe Rider', alentando a los pasajeros a informar cualquier problema directamente al personal."),

        // MARK: - CIUDADES DE CANADÁ (2)
        
        // Toronto

        NewsArticle(city: "Toronto", title: "Servicio de Policía de Toronto Anuncia Plan de Seguridad 'Safe TO'", author: "Sarah Jenkins", imageName: "Toronto", fullText: "El Servicio de Policía de Toronto ha lanzado 'Safe TO', su plan de seguridad oficial para la Copa del Mundo. La estrategia implica un aumento significativo de la presencia de oficiales en el núcleo del centro, en las zonas de fans y alrededor del BMO Field. El plan también incluye una campaña de concienciación pública sobre seguridad personal y cómo informar actividades sospechosas. Una línea directa de apoyo al visitante, multilingüe y dedicada, estará activa 24/7 para ayudar a los turistas con cualquier inquietud de seguridad que puedan tener durante su estadía en la ciudad."),

        NewsArticle(city: "Toronto", title: "Perímetro del BMO Field Contará con Cercado 'Inteligente'", author: "Li Wang", imageName: "Toronto", fullText: "El perímetro expandido alrededor del BMO Field contará con un cercado 'inteligente' equipado con sensores y cámaras. Esta tecnología puede detectar si alguien trepa, corta o manipula la cerca y alertará automáticamente al centro de comando de seguridad con una transmisión de video en vivo de la ubicación específica. Esto permite una respuesta rápida a cualquier posible violación de la capa de seguridad exterior del estadio. Es una medida proactiva diseñada para asegurar el recinto mucho antes de que alguien llegue a las puertas de entrada."),

        NewsArticle(city: "Toronto", title: "GO Transit y TTC Desplegarán Agentes Especiales", author: "Tom Gordon", imageName: "Toronto", fullText: "Tanto GO Transit como la Comisión de Tránsito de Toronto (TTC) desplegarán toda su fuerza de Agentes Especiales (Special Constables) durante el torneo. Estos oficiales tendrán una presencia de alta visibilidad en los principales centros como Union Station y en todas las rutas que sirven a Exhibition Place. Su enfoque estará en la gestión de multitudes y en garantizar la seguridad de los pasajeros. Este esfuerzo coordinado entre las dos principales agencias de tránsito es vital para asegurar el movimiento de millones de personas en toda el Área Metropolitana de Toronto."),

        // Vancouver
        NewsArticle(city: "Vancouver", title: "Vancouver Adopta Modelo de 'Unidad de Seguridad Integrada'", author: "Emily Carr", imageName: "Vancouver", fullText: "Siguiendo el modelo de eventos importantes anteriores en la ciudad, Vancouver establecerá una Unidad de Seguridad Integrada (ISU) para la Copa del Mundo. Esta unidad reúne a oficiales del Departamento de Policía de Vancouver, la RCMP (Policía Montada) y otras agencias bajo una estructura de comando única y unificada. La ISU será responsable de todos los aspectos de la seguridad del torneo, desde las operaciones del estadio hasta la protección de las zonas públicas de fans, asegurando una respuesta coordinada y efectiva a cualquier situación que pueda surgir."),

        NewsArticle(city: "Vancouver", title: "BC Place Aplicará Política de Revisión de Bolsos al 100%", author: "Mike O'Brian", imageName: "Vancouver", fullText: "El BC Place ha confirmado que se aplicará una política de revisión del 100% para todos los bolsos que ingresen al estadio. Si bien se recomienda encarecidamente el uso de bolsos transparentes para acelerar la entrada, todos los bolsos estarán sujetos a una minuciosa revisión física por parte del personal de seguridad. Esta estricta política está en vigor para evitar que cualquier artículo prohibido ingrese al recinto. Se establecerán múltiples carriles de revisión para gestionar el proceso de la manera más eficiente posible, y se aconseja a los fanáticos que lleguen temprano para evitar retrasos."),

        NewsArticle(city: "Vancouver", title: "Estaciones de SkyTrain Contarán con Vigilancia Mejorada", author: "Chloe Kim", imageName: "Vancouver", fullText: "Todas las estaciones de SkyTrain, especialmente aquellas en la Línea Expo que sirve al BC Place, contarán con vigilancia mejorada y una mayor presencia de la Policía de Tránsito. TransLink está actualizando muchas de sus cámaras de estación a modelos de alta definición y tendrá personal monitoreando activamente las transmisiones en tiempo real. El objetivo es crear un entorno de tránsito seguro donde los fanáticos se sientan seguros viajando hacia y desde los partidos, sabiendo que el sistema está siendo vigilado de cerca para prevenir cualquier incidente."),

        // MARK: - CIUDADES DE MÉXICO (3)

        // Guadalajara
        NewsArticle(city: "Guadalajara", title: "Policía Estatal de Jalisco Liderará Esfuerzo de Seguridad Regional", author: "Ana Cruz", imageName: "Guadalajara", fullText: "La Policía Estatal de Jalisco tomará la iniciativa en un esfuerzo de seguridad regional, coordinándose con las policías municipales de Guadalajara, Zapopan y Tlaquepaque. Esta operación conjunta garantizará una cobertura de seguridad consistente en toda el área metropolitana. Más de 5,000 oficiales se dedicarán a tareas de la Copa del Mundo, centrándose en proteger hoteles, áreas turísticas y las rutas que conducen al Estadio Akron. Las fuerzas federales también estarán disponibles para proporcionar apoyo adicional y capacidades de inteligencia."),

        NewsArticle(city: "Guadalajara", title: "Estadio Akron Implementa Zona de Seguridad de Triple Revisión", author: "Javier Solis", imageName: "Guadalajara", fullText: "Se establecerá una zona de seguridad de triple revisión alrededor del Estadio Akron en los días de partido. El primer punto de control revisará vehículos lejos del estadio. El segundo será una revisión de boletos y credenciales para peatones. El punto de control final en las puertas del estadio implicará una revisión personal y de bolsos completa. Este enfoque por capas está diseñado para filtrar cualquier amenaza potencial mucho antes de que puedan acercarse al recinto, creando una burbuja segura para que los fanáticos disfruten de los partidos."),

        NewsArticle(city: "Guadalajara", title: "Policía Turística Patrullará el Centro Histórico", author: "Elena Fuentes", imageName: "Guadalajara", fullText: "Una unidad especial de la Policía Turística, con oficiales bilingües, se desplegará por todo el centro histórico de Guadalajara. Estos oficiales están específicamente capacitados para ayudar a los visitantes internacionales, proporcionando direcciones, información y una sensación de seguridad. Serán fácilmente identificables y estarán estacionados cerca de puntos de referencia clave como la catedral, la Plaza de Armas y el Hospicio Cabañas. Su presencia tiene como objetivo garantizar que todos los visitantes tengan una experiencia segura y agradable mientras exploran la rica cultura de la ciudad."),

        // Ciudad de México
        NewsArticle(city: "Ciudad de México", title: "Secretaría de Seguridad Ciudadana Despliega 10,000 Oficiales", author: "Lalo Cardenas", imageName: "Ciudad de México", fullText: "La Secretaría de Seguridad Ciudadana (SSC) de la Ciudad de México ha anunciado el despliegue de 10,000 oficiales de policía específicamente para la seguridad de la Copa del Mundo. Esta operación masiva involucrará a oficiales de unidades de tránsito, turísticas y de operaciones especiales. Su enfoque principal será asegurar el Estadio Azteca, el 'fan fest' del Zócalo y los principales centros de transporte como el aeropuerto y las principales estaciones de metro. Esto representa uno de los despliegMues de seguridad más grandes en la historia reciente de la ciudad."),

        NewsArticle(city: "Ciudad de México", title: "Estadio Azteca Usará Tecnología de Reconocimiento Facial", author: "Sofia Reyes", imageName: "Ciudad de México", fullText: "Como parte de su importante renovación, el Estadio Azteca está instalando un nuevo sistema de reconocimiento facial en todas las entradas. Esta tecnología se utilizará para identificar a individuos que estén en listas de vigilancia de seguridad o que hayan sido previamente vetados de eventos deportivos. Aunque es opcional para la mayoría de los fanáticos, el sistema agrega una poderosa capa de seguridad para evitar que conocidos alborotadores ingresen al estadio. Las autoridades han enfatizado que los datos se manejarán de acuerdo con las leyes de privacidad y se usarán exclusivamente con fines de seguridad."),

        NewsArticle(city: "Ciudad de México", title: "Guardia Nacional Asegurará 'Líneas de Fútbol' del Metro", author: "Ricardo Morales", imageName: "Ciudad de México", fullText: "La Guardia Nacional de México asistirá con la seguridad a lo largo del sistema de Metro de la ciudad, con un enfoque particular en las 'Líneas de Fútbol' especiales que sirven al Estadio Azteca. Los soldados estarán estacionados en puntos de transferencia clave y en la estación del estadio para gestionar multitudes y proporcionar una presencia de seguridad visible. Esta colaboración entre la policía de la ciudad y las fuerzas federales está diseñada para garantizar el transporte seguro y ordenado de millones de fanáticos que dependerán del Metro para llegar al histórico recinto."),

    NewsArticle(city: "Monterrey", title: "Fuerza Civil Anuncia Operativo 'Estadio Seguro'", author: "Miguel Garza", imageName: "Monterrey", fullText: "La fuerza policial estatal de Nuevo León, Fuerza Civil, ha anunciado su operativo 'Estadio Seguro' para la Copa del Mundo. El plan implica crear un perímetro seguro alrededor del Estadio BBVA y gestionar el flujo de tráfico en las autopistas circundantes. Helicópteros estatales proporcionarán vigilancia aérea los días de partido, y unidades especiales estarán en espera para responder a cualquier incidente importante. El gobernador ha declarado que garantizar un ambiente seguro y familiar es la máxima prioridad del estado."),
    
    NewsArticle(city: "Monterrey", title: "Estadio BBVA Exigirá Fan ID para Entrar", author: "Isabella Garza", imageName: "Monterrey", fullText: "Además de un boleto para el partido, todos los fanáticos que ingresen al Estadio BBVA deberán presentar un Fan ID registrado. Este sistema, que se ha utilizado con éxito en la Liga MX, vincula un boleto a una persona específica e identificada, ayudando a prevenir el fraude de boletos y a rastrear a cualquier persona involucrada en mala conducta. El registro para el Fan ID debe completarse en línea antes de llegar al estadio. Esta medida es una parte clave del esfuerzo por eliminar la violencia y el comportamiento indisciplinado de los estadios de fútbol."),
    
    NewsArticle(city: "Monterrey", title: "Aumenta Seguridad en Fan Zone de Parque Fundidora", author: "Pedro Ramirez", imageName: "Monterrey", fullText: "Se ha implementado un sólido plan de seguridad para la zona de fans oficial en el Parque Fundidora. El parque tendrá puntos de acceso controlados con detectores de metales y revisiones de bolsos. Tanto la seguridad privada como los oficiales de Fuerza Civil patrullarán los terrenos para garantizar un entorno seguro para las decenas de miles de fanáticos que se espera se reúnan allí. La naturaleza extensa y abierta del parque presenta desafíos de seguridad únicos, que los funcionarios dicen estar completamente preparados para manejar durante todo el torneo.")
    ]
}
